### ISSUE TITLE
Upcoming end of life for what3words API v1

### ISSUE THREAD

**Issue by vicchi** [lucidstack/w3w-elixir-wrapper#1]
Hi there,

This repo's what3words API wrapper is currently using v1 of the what3words API. This version was deprecated on 1/6/16 and will be switched off on 30/11/16.

This is just a heads up that this is coming up; please see https://docs.what3words.com/api/v1/#version for more information.

**Comment by lucidstack** [comment]
Hello there,

Thank you for the heads up! I've been meaning to update this package since the release of v2, and never found the time. Well, clock is ticking, better get onto this now! Will keep you updated! ✌️

**Comment by lucidstack** [comment]
Hi @vicchi,

I'm now released version 2.0.0 of the library, that uses the `/v2` endpoints, and adds the autosuggest functionality. I'm gonna open issues for the StandardBlend and Grid endpoints, and I'll tackle them as soon as I have some spare time.

Thanks again for creating this amazing service, you're changing the world!

**Comment by vicchi** [comment]
@lucidstack - That's great - thanks for doing this and for the kind words!
